image: alpine:latest    # Ideally, a dedicated docker image with Truffle on it

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make
 - npm i -g truffle ganache-cli run-with-testrpc solhint
 - npm i

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - node_modules/

stages:
  - build
  - checkstyle
  - test
  - coverage
  - deploy

coverage:
  stage: coverage
  only:
    - develop
  tags: [aireach]
  script:
    - npm run coverage
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - develop  

checkstyle:
  stage: checkstyle
  tags: [aireach]
  script:
    - npm run linting

build:
  stage: build
  tags: [aireach]
  script:
    - npm run build
  artifacts:
    paths:
      - build

test:
 stage: test
 tags: [aireach]
 script:
   - npm test

deploy:
 stage: deploy
 tags: [aireach]
 script:
   - npm run deploy
